app: marierealtest
ssh_url: marierealtest@deploy.eu2.frbit.com
ssh_path: null
git_remote: marierealtest/master
before:
    code/up:
        - 'echo  "Script example: " $(git rev-parse HEAD)'
after:
    code/down:
        - 'php craft migrate/all'
